#!/usr/bin/env python3
"""Package compiled artifacts into a .yxzp archive."""

from __future__ import annotations

import argparse
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile


def _write_directory_marker(zip_handle: ZipFile, target_dir: str) -> None:
    """Ensure empty directories appear in the archive."""
    if not target_dir.endswith("/"):
        target_dir = f"{target_dir}/"
    zip_handle.writestr(target_dir, "")


def _add_directory(zip_handle: ZipFile, source_dir: Path, target_dir: str) -> None:
    """Add all files from source_dir to target_dir in the archive."""
    if not source_dir.exists():
        _write_directory_marker(zip_handle, target_dir)
        return

    has_files = False
    for path in sorted(source_dir.rglob("*")):
        if path.is_file():
            rel = path.relative_to(source_dir).as_posix()
            zip_handle.write(path, f"{target_dir}/{rel}")
            has_files = True

    if not has_files:
        _write_directory_marker(zip_handle, target_dir)


def create_package(
    source_dir: Path,
    output_path: Path,
    data_dir: Path | None = None,
    docs_readme: Path | None = None,
    macros_dir: Path | None = None,
) -> Path:
    """Create a .yxzp bundle from compiled artifacts."""
    source_dir = source_dir.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    main_yxmd = source_dir / "main.yxmd"
    if not main_yxmd.exists():
        raise FileNotFoundError(f"Missing required file: {main_yxmd}")

    workflow_spec = source_dir / "workflow_spec.json"
    validation_report = source_dir / "validation_report.json"

    data_dir = data_dir or (source_dir / "data")
    macros_dir = macros_dir or (source_dir / "macros")

    if docs_readme is None:
        docs_readme = source_dir / "README.md"

    if docs_readme.exists():
        readme_text = docs_readme.read_text(encoding="utf-8")
    else:
        readme_text = (
            "# Generated Alteryx Package\n\n"
            "This bundle was generated by alteryx-workflow-builder.\n"
            "Contents include compiled workflow XML and optional data/macros.\n"
        )

    with ZipFile(output_path, "w", compression=ZIP_DEFLATED) as bundle:
        bundle.write(main_yxmd, "workflows/main.yxmd")
        if workflow_spec.exists():
            bundle.write(workflow_spec, "workflows/workflow_spec.json")
        if validation_report.exists():
            bundle.write(validation_report, "workflows/validation_report.json")

        _add_directory(bundle, data_dir, "data")
        bundle.writestr("docs/README.md", readme_text)
        _add_directory(bundle, macros_dir, "macros")

    return output_path


def parse_args() -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(description="Package artifacts into a .yxzp archive")
    parser.add_argument("--source_dir", required=True, type=Path, help="Directory containing main.yxmd")
    parser.add_argument("--out", required=True, type=Path, help="Output .yxzp path")
    parser.add_argument("--data_dir", type=Path, default=None, help="Optional data directory")
    parser.add_argument("--docs_readme", type=Path, default=None, help="Optional docs README path")
    parser.add_argument("--macros_dir", type=Path, default=None, help="Optional macros directory")
    return parser.parse_args()


def main() -> int:
    """CLI entry point."""
    args = parse_args()
    result = create_package(
        source_dir=args.source_dir,
        output_path=args.out,
        data_dir=args.data_dir,
        docs_readme=args.docs_readme,
        macros_dir=args.macros_dir,
    )
    print(f"Wrote {result}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
